In [3]:
import numpy as np

NumPy is a general-purpose array-processing Python library which provides handy methods/functions for working n-dimensional arrays. NumPy is a short form for “Numerical Python“. It provides various computing tools such as comprehensive mathematical functions, and linear algebra routines

# What is the benefit of using NumPy?

* **Efficiency**: NumPy’s arrays are stored in contiguous memory, allowing for faster access and manipulation compared to traditional Python lists.
* **Vectorized operations**: NumPy allows you to perform operations on entire arrays at once, significantly improving performance.
* **Versatility**: NumPy provides a wide range of mathematical functions, data types, and array manipulation tools.
* **Ease of use**: NumPy’s syntax is straightforward and intuitive, making it easy to learn and use.
* **Integration**: NumPy integrates seamlessly with other popular scientific libraries like SciPy, Pandas, and Matplotlib.

# Creating ndarrays

The easiest way to create an array is to use the array function. This accepts any sequence-like object and produces a new NumPy array containing the passed data. For example, a list is a good candidate for conversion:

In [4]:
data1 = [6, 7.5, 8, 0, 1]

In [5]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

# 1D NumPy Array:

A 1D NumPy array is essentially a list of elements. It has a single dimension, like a vector in mathematics.

In [6]:
# Creating a 1D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)
arr_1d.ndim

[1 2 3 4 5]


1

# 2D NumPy Array:

A 2D NumPy array is a grid of elements, where each row is a 1D array. It's like a matrix with rows and columns

In [7]:
# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d)
arr_2d.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

# 3D NumPy Array:

A 3D NumPy array is like a cube of elements, with multiple 2D arrays stacked together. It can be visualized as multiple matrices arranged in layers

In [8]:
# Creating a 3D NumPy array
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]],
                   [[13, 14, 15],
                    [16, 17, 18]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [9]:
arr_3d.ndim

3

In [10]:
arr_3d.shape

(3, 2, 3)

# Axes in Numpy
NumPy arrays can have multiple dimensions, but to perform operations on specific parts of the array, we need a way to reference them. This is where axes come in. Axes are essentially the dimensions along which a NumPy array is organized, similar to how a coordinate system works.

In a 2-dimensional array, which is the most common scenario, we have two axes:

**Axis 0 (vertical):** Represents the rows of the array.

**Axis 1 (horizontal):** Represents the columns of the array.
Here's a code snippet to create a 2D array and access elements by axis:

In [12]:
# Create a 2D array
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Accessing elements by axis
print(data[0, 1])  # Access element at row 0 (first row), column 1 (second column)
print(data[1])  # Access all elements in row 1 (second row)
print(data[:, 2])  # Access all elements in column 2 (third column)

2
[4 5 6]
[3 6 9]


As you can see, we can access individual elements using their row and column indices, or we can access entire rows or columns by specifying the axis.

# Operations along Axes

Many NumPy functions operate along axes. By specifying the axis argument, you can control whether the operation is performed across rows (axis=0) or columns (axis=1).

For example, let's calculate the mean of each row and column of the array:



In [13]:
# Find mean of each row (axis=0)
mean_of_rows = np.mean(data, axis=0)

# Find mean of each column (axis=1)
mean_of_columns = np.mean(data, axis=1)

print(mean_of_rows)
print(mean_of_columns)

[4. 5. 6.]
[2. 5. 8.]


Here, `np.mean(data, axis=0)` calculates the mean along axis 0 (rows), resulting in a new array with the average values of each column. Similarly, `np.mean(data, axis=1)` calculates the mean along axis 1 (columns), giving us the average values of each row.

# Higher Dimensional Arrays

The concept of axes extends to higher dimensional arrays as well. For instance, a 3D array would have three axes: axis 0 for rows, axis 1 for columns, and axis 2 for depth (or "slices"). Operations can be performed along any of these axes.

By understanding axes, you can effectively manipulate and analyze data in NumPy arrays. Remember, axis 0 refers to rows and axis 1 refers to columns in most cases. This is a fundamental concept for working with NumPy arrays!


---



Unless explicitly specified, np.array tries to infer a good data type for the array that it creates. The data type is stored in a special dtype object; for example, in the above two examples:

In [15]:
arr_2d.dtype

dtype('int64')

In [16]:
arr3 = np.array([1, 2, 3], dtype=np.float64)
arr3

array([1., 2., 3.])

In [17]:
arr4 = np.array([1, 2, 3], dtype=np.int32)
arr4

array([1, 2, 3], dtype=int32)

In [18]:
arr3.dtype

dtype('float64')

In [19]:
arr4.dtype

dtype('int32')

In addition to np.array, there are a number of other functions for creating new arrays. As examples, zeros and ones create arrays of 0’s or 1’s, with a given length or shape. empty creates an array without initializing its values to any particular value.

To create a higher dimensional array with these methods, pass a tuple for the shape:

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.empty((2, 3, 2))

array([[[4.7870254e-310, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000]],

       [[0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000]]])

arange is an array-valued version of the built-in Python range function:

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Type conversion of ndarrays


An array can be explicitly converted or casted from one dtype to another using ndarray’s astype method:

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [25]:
float_arr = arr.astype(np.float64)
float_arr.dtype

float_arr

dtype('float64')

In this example, integers were cast to floating point. If some floating point numbers are casted to be of integer dtype, the decimal part will be truncated:

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.dtype

dtype('float64')

In [ ]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In case of an array of strings representing numbers, astype can be used to convert them to numeric form:

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)


array([ 1.25, -9.6 , 42.  ])

In [ ]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [ ]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

There are shorthand type code strings that can also be used to refer to a dtype:

In [ ]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

# Operations between Arrays and Scalars

Arrays are important because they enable to express batch operations on data without writing any for loops. This is usually called vectorization. Any arithmetic operations between equal-size arrays applies the operation elementwise:

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Arithmetic operations with scalars propagate the value to each element:

In [ ]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

# Basic Indexing and Slicing

NumPy array indexing is a rich topic, as there are many ways to select a subset of data or individual elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
arr[5:8]

array([5, 6, 7])

In [ ]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

It can be seen if a scalar value is assigned to a slice, as in arr[5:8] = 12, the value is propagated to the entire selection. An important first distinction from lists is that array slices are views on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array:

In [ ]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [ ]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [ ]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

With higher dimensional arrays, there are many more options. In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays:

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d.shape
arr2d[2]

array([7, 8, 9])

Thus, individual elements can be accessed recursively. But that is a bit too much work, so a comma-separated list of indices can be passed to select individual elements. So these are equivalent:

In [ ]:
arr2d[0][2]

3

In multidimensional arrays, if later indices are omitted, the returned object will be a lower dimensional
ndarray consisting of all the data along the higher dimensions. So in the 2 × 2 × 3 array arr3d

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11,
12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

arr3d[0] is a 2 × 3 array:

In [ ]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

Both scalar values and arrays can be assigned to arr3d[0]:

In [ ]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Similarly, arr3d[1, 0] gives all of the values whose indices start with (1, 0), forming a 1-dimensional
array:

In [ ]:
arr3d[1, 0]

array([7, 8, 9])

In all of these cases where subsections of the array have been selected, the returned arrays are views.

# Slicing




Slicing refers to selecting a portion of the array using the colon : operator. The general syntax for slicing is array[start:stop:step], where start is the index to start from (inclusive), stop is the index to stop before (exclusive), and step is the step size between elements

# Slicing 1D-array

In [ ]:
# Creating a NumPy array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Basic slicing
slice1 = arr[2:6]  # Elements from index 2 to 5
print(slice1)  # Output: [2 3 4 5]

[2 3 4 5]


In [ ]:
# Slicing with step
slice2 = arr[1:8:2]  # Elements from index 1 to 7 with a step of 2
print(slice2)  # Output: [1 3 5 7]

[1 3 5 7]


In [ ]:
# Slicing with negative step
slice3 = arr[8:2:-1]  # Elements from index 8 to 3 with a step of -1
print(slice3)  # Output: [8 7 6 5 4 3]

[8 7 6 5 4 3]


In [ ]:
# Omitting start and stop indices
slice4 = arr[:5]  # Elements from the beginning up to index 4
print(slice4)  # Output: [0 1 2 3 4]

[0 1 2 3 4]


In [ ]:

slice5 = arr[5:]  # Elements from index 5 to the end
print(slice5)  # Output: [5 6 7 8 9]

[5 6 7 8 9]


# Slicing 2D-array

In [ ]:
# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
# Selecting specific rows and columns
slice_2d_1 = arr_2d[0:2, 1:3]  # Rows 0 and 1, columns 1 and 2
print(slice_2d_1)

[[2 3]
 [5 6]]


In [ ]:
# Omitting start and stop indices for rows and columns
slice_2d_2 = arr_2d[:, 1:]  # All rows, columns from index 1 to the end
print(slice_2d_2)

[[2 3]
 [5 6]
 [8 9]]


In [ ]:
# Slicing along one dimension
slice_2d_3 = arr_2d[1, :]  # Selecting the second row
print(slice_2d_3)

[4 5 6]


In [ ]:
slice_2d_4 = arr_2d[:, 2]  # Selecting the third column
print(slice_2d_4)

[3 6 9]


In [ ]:
# Slicing with step
arr_2d_2 = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

slice_2d_5 = arr_2d_2[::2, ::2]  # Selecting every other row and column
print(slice_2d_5)

[[ 1  3]
 [ 9 11]]


In [ ]:
# Slicing with negative step

slice_2d_6 = arr_2d_2[::-1, ::-1]  # Reversing both rows and columns
print(slice_2d_6)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


# Slicing 3D-array

In [ ]:
# Creating a 3D NumPy array
import numpy as np
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                    [[7, 8, 9], [10, 11, 12]],
                    [[13, 14, 15], [16, 17, 18]]])

print(arr_3d.shape)

# Selecting specific elements
slice_3d_1 = arr_3d[1, 0, 2]  # Selecting element at index (1, 0, 2)
print(slice_3d_1)

(3, 2, 3)
9


In [ ]:
# Slicing along one dimension
slice_3d_2 = arr_3d[0, :, :]  # Selecting all elements from the first "slice" (2D array)
print(slice_3d_2)

[[1 2 3]
 [4 5 6]]


In [ ]:
slice_3d_3 = arr_3d[:, :, 1]  # Selecting the second column from all "slices"
print(slice_3d_3)

[[ 2  5]
 [ 8 11]
 [14 17]]


In [ ]:
# Slicing with step
arr_3d_2 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],
                     [[9, 10, 11, 12], [13, 14, 15, 16]],
                     [[17, 18, 19, 20], [21, 22, 23, 24]]])

In [ ]:
slice_3d_4 = arr_3d_2[:, ::2, ::2]  # Selecting every other row and column from all "slices"
print(slice_3d_4)

[[[ 1  3]]

 [[ 9 11]]

 [[17 19]]]


In [ ]:
# Slicing with negative step
slice_3d_5 = arr_3d_2[::-1, ::-1, ::-1]  # Reversing all dimensions
print(slice_3d_5)

[[[24 23 22 21]
  [20 19 18 17]]

 [[16 15 14 13]
  [12 11 10  9]]

 [[ 8  7  6  5]
  [ 4  3  2  1]]]


Discuss Fig 1.3 in lab workbook

# Reshaping Arrays

An array can be converted from one shape to another without copying any data. To do this, pass a tuple indicating the new shape to the reshape array instance method. For example, suppose there is a one-dimensional array of values to rearrange into a matrix:

In [ ]:
arr = np.arange(8)
arr


array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr.reshape((4, 2))


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
arr.reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

One of the passed shape dimensions can be -1, in which case the value used for that dimension will be inferred from the data:

In [ ]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Flattening or raveling a NumPy array refers to the process of converting a multi-dimensional array into a one-dimensional array. This means that all the elements of the array are placed in a single, linear sequence. In NumPy, you can achieve this using the flatten() or ravel() function

flatten(): This function returns a copy of the array collapsed into one dimension. It always returns a copy of the original array, even if the array is already one-dimensional. Therefore, modifications to the flattened array do not affect the original array.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print(flattened_arr)



[1 2 3 4 5 6]


ravel(): This function returns a one-dimensional view of the input array. If modifications are made to the resulting array, they will affect the original array as well, since ravel() returns a view rather than a copy whenever possible. However, if the resulting array is modified in such a way that it cannot be represented as a contiguous slice of the original array, a copy will be made.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
raveled_arr = arr.ravel()
print(raveled_arr)


[1 2 3 4 5 6]


# Concatenating and Splitting Arrays

numpy.concatenate takes a sequence (tuple, list, etc.) of arrays and joins them together in order along the input axis.

*   When axis=0, it means that arrays will be concatenated along the first axis, which is typically the rows axis. This means that arrays will be stacked vertically on top of each other.

*   When axis=1, it means that arrays will be concatenated along the second axis, which is typically the columns axis. This means that arrays will be stacked side by side.



In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

The np.split() function in NumPy is used to split an array into multiple sub-arrays along a specified axis

In [ ]:
# Create an array
arr = np.arange(10)

# Split the array into 5 equal-sized sub-arrays
sub_arrays = np.split(arr, 5)
print("Split array into 5 sub-arrays:")
for sub_arr in sub_arrays:
    print(sub_arr)

Split array into 5 sub-arrays:
[0 1]
[2 3]
[4 5]
[6 7]
[8 9]


In this example, the np.split() function splits the array arr into 5 equal-sized sub-arrays along the default axis (axis 0), resulting in arrays with two elements each

You can also specify the axis along which to split the array. Here's an example of splitting a 2D array along the columns axis (axis 1):

In [ ]:
#Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Split the array along axis 1 (columns)
sub_arrays = np.split(arr_2d, 3, axis=1)
print("Split array along columns (axis=1):")
for sub_arr in sub_arrays:
    print(sub_arr)

Split array along columns (axis=1):
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


# Transposing Arrays and Swapping Axes

Transposing is a special form of reshaping which similarly returns a view on the underlying data without copying anything. Arrays have the transpose method and also the special T attribute

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Simple transposing with .T is just a special case of swapping axes. ndarray has the method swapaxes which takes a pair of axis numbers:

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))
arr


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

The original array arr has shape (2, 2, 4), where:


*   The first axis (axis 0) has length 2
*   The second axis (axis 1) has length 2,
*   The third axis (axis 2) has length 4.

By swapping axes 1 and 2, you are effectively transposing the last two dimensions. The resulting array will have shape (2, 4, 2).




# Mathematical and Statistical methods

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
# Sum of all elements in the array
print("Sum:", np.sum(arr))

# Mean of the array
print("Mean:", np.mean(arr))

# Standard deviation of the array
print("Standard Deviation:", np.std(arr))

# Square root of each element in the array
print("Square Root:", np.sqrt(arr))



Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Minimum value in the array
print("Minimum:", np.min(arr_2d))

# Maximum value in the array
print("Maximum:", np.max(arr_2d))

# Mean along a specific axis (axis=0 means along columns)
print("Mean along axis 0:", np.mean(arr_2d, axis=0))

# Standard deviation along a specific axis (axis=1 means along rows)
print("Standard Deviation along axis 1:", np.std(arr_2d, axis=1))

Minimum: 1
Maximum: 6
Mean along axis 0: [2.5 3.5 4.5]
Standard Deviation along axis 1: [0.81649658 0.81649658]


# Linear Algebra

 NumPy provides a comprehensive set of functions for linear algebra operations.

In [ ]:
# Creating a 2x2 matrix
A = np.array([[1, 2],
              [3, 4]])

# Creating a 1D vector
v = np.array([5, 6])

In [ ]:
# Matrix multiplication
result = np.dot(A, v)
print("Matrix-vector multiplication:")
print(result)

Matrix-vector multiplication:
[17 39]


In [ ]:
# Transpose of a matrix
transpose_A = np.transpose(A)
print("Transpose of A:")
print(transpose_A)

Transpose of A:
[[1 3]
 [2 4]]


In [ ]:
# Matrix inverse
inverse_A = np.linalg.inv(A)
print("Inverse of A:")
print(inverse_A)

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# Determinant of a matrix
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: -2.0000000000000004


In [ ]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:", eigenvectors)

Eigenvalues of A: [-0.37228132  5.37228132]
Eigenvectors of A: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# Solving linear equations: Ax = b
b = np.array([7, 8])
solution = np.linalg.solve(A, b)
print("Solution of Ax = b:", solution)

Solution of Ax = b: [-6.   6.5]


# File Input and Output with Arrays

NumPy is able to save and load data to and from disk either in text or binary format

In [ ]:
arr = np.arange(10)
np.save('some_array', arr)

If the file path does not already end in .npy, the extension will be appended. The array on disk can then be loaded using np.load:

In [ ]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Multiple arrays are saved in a zip archive using np.savez and passing the arrays as keyword arguments:

In [ ]:
np.savez('array_archive.npz', a=arr, b=arr)

When loading an .npz file, a dict-like object is got back which loads the individual arrays lazily:

In [ ]:
arch = np.load('array_archive.npz')

In [ ]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Saving and Loading Text Files

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
arr = np.loadtxt('/content/drive/My Drive/Colab Notebooks/arr_ex.txt', delimiter=',')
arr


array([[ 0.580052,  0.18673 ,  1.040717,  1.134411],
       [ 0.194163, -0.636917, -0.938659,  0.124094],
       [-0.12641 ,  0.268607, -0.695724,  0.047428],
       [-1.484413,  0.004176, -0.744203,  0.005487],
       [ 2.302869,  0.200131,  1.670238, -1.88109 ],
       [-0.19323 ,  1.047233,  0.482803,  0.960334]])

np.savetxt performs the inverse operation: writing an array to a delimited text file

# Broadcasting

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations

In [ ]:
x = np.array([[0], [1], [2]])
y = np.array([[3, 4, 5]])

In [ ]:
print(x)
print(y)

[[0]
 [1]
 [2]]
[[3 4 5]]


In [ ]:
x + y

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

# Shape Compatibility Rules

1.   If x, y have a different number of dimensions, prepend 1's to the shape of the shorter.
2.   Any axis of length 1 can be repeated (broadcast) to the length of the other vector's length in that axis
3. All other axes must have matching lengths.

Use these rules to compute whether the arrays are compatible and, if so, the broadcasted shape.



In [ ]:
x.shape == (2, 3)

y.shape == (2, 3)  # compatible
y.shape == (2, 1)  # compatible
y.shape == (1, 3)  # compatible
y.shape == (3,)  # compatible

# results in (2, 3) shape

y.shape == (3, 2)  # NOT compatible
y.shape == (2,)  # NOT compatible

False

In [ ]:
x.shape == (1000, 256, 256, 256)

y.shape == (1000, 256, 256, 256)  # compatible
y.shape == (1000, 1, 256, 256)  # compatible
y.shape == (1000, 1, 1, 256)  # compatible
y.shape == (1, 256, 256, 256)  # compatible
y.shape == (1, 1, 256, 1)  # compatible

# results in (1000, 256, 256, 256) shape

y.shape == (1000, 256, 256)  # NOT compatible

False

In [ ]:
x.shape == (1, 2, 3, 5, 1, 11, 1, 17)
y.shape ==          (1, 7, 1,  1, 17)  # compatible

# results in shape (1, 2, 3, 5, 7, 11, 1, 17)

False

# Once shapes match, use for-loop to understand

For any axis with length 1, use the only possible value.

In [ ]:
x = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
y = np.array([1, 10, 100]).reshape(3, 1)

print(x + y)

# x     (3, 3)
# y     (3, 1)
shape = (3, 3)
out = np.empty(shape, dtype=int)
N0, N1 = shape
for i in range(N0):
    for j in range(N1):
        # in the dimension that y only has 1 element, just use it
        out[i, j] = x[i, j] + y[i, 0]
print(out)

[[  1   2   3]
 [ 13  14  15]
 [106 107 108]]
[[  1   2   3]
 [ 13  14  15]
 [106 107 108]]


Just omit variables for prepended 1's.

In [ ]:
x = np.array([[[0, 1, 2],
               [3, 4, 5],
               [6, 7, 8]],
              [[9, 10, 11],
               [12, 13, 14],
               [15, 16, 17]]])  # shape (2, 3, 3)
y = np.array([1, 10, 100])     # shape       (3,)

print(x + y)

# align and prepend
# x     (2, 3, 3)
# y     (1, 1, 3)
shape = (2, 3, 3)
out = np.empty(shape, dtype=int)
N0, N1, N2 = shape
for i in range(N0):
    for j in range(N1):
        for k in range(N2):
            # leave off prepended indices of y
            out[i, j, k] = x[i, j, k] + y[k]
print(out)

[[[  1  11 102]
  [  4  14 105]
  [  7  17 108]]

 [[ 10  20 111]
  [ 13  23 114]
  [ 16  26 117]]]
[[[  1  11 102]
  [  4  14 105]
  [  7  17 108]]

 [[ 10  20 111]
  [ 13  23 114]
  [ 16  26 117]]]


Both arrays can have broadcasted axes, not just one.

In [ ]:
x = np.array([[0], [1], [2]])  # (3, 1)
y = np.array([[3, 4, 5]])     # (1, 3)

print(x + y)

shape = (3, 3)
out = np.empty(shape, dtype=int)
N0, N1 = shape
for i in range(N0):
    for j in range(N1):
        out[i, j] = x[i, 0] + y[0, j]
print(out)

[[3 4 5]
 [4 5 6]
 [5 6 7]]
[[3 4 5]
 [4 5 6]
 [5 6 7]]


Reference:

https://www.youtube.com/watch?v=oG1t3qlzq14
https://github.com/mCodingLLC/VideosSampleCode/blob/master/videos/032_numpy_broadcasting_explained/numpy_broadcasting.ipynb